name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout of Changes
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare Dependency Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''**/*.gradle'') }}'
          restore-keys: '${{ runner.os }}-gradle'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Setup Decomp Workspace
        run: ./gradlew setupDecompWorkspace

      - name: Build with Gradle
        run: ./gradlew build
   
