name: gradle

on:
  push:
    branches:
      - 'master'

jobs:
  gill_bates:
    runs-on: ubuntu-latest
    steps:

      - name: checkout changes
        uses: actions/checkout@v2

      - name: get commit info
        run: echo "SHA=$GITHUB_SHA" >> $GITHUB_ENV

      - name: prepare release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: automated release at commit ${{ env.SHA }}
          draft: false
          prerelease: false

      - name: prepare java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: prepare depdendency cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''**/*.gradle'') }}'
          restore-keys: '${{ runner.os }}-gradle'

      - name: gradle setup decomp workspace
        run: ./gradlew setupDecompWorkspace

      - name: gradle build
        run: ./gradlew build --stacktrace --info

      - name: upload release
        uses: csexton/release-asset-action@v2
        with:
          pattern: "build/libs/Konas-*-release.jar"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
